### ISSUE TITLE
Question around omitting -shell from 2.24

### ISSUE THREAD

**Issue by mauritslamers** [codello/docker-lilypond#27]
Hi,

I have a question around the omission of the -shell version of the docker image 2.24. I am using the docker image to run Lilypond against a specific test suite of lilypond files as part of a CI-process. For this, the -shell docker image version is ideal, as I just have to run a shell script running the tests. Not having to create another docker around it is really helpful.

Would you consider adding this feature again?

**Comment by codello** [comment]
Hi, thanks for the question.

The main reason for omitting the `-shell` variant was that I didn't see a good reason to keep it around when the non-shell variant could basically serve the same purpose. There were two main differences between the two variants:
1. The `-shell` variant had some additional packages preinstalled (such as `make`, `jq`, or `unzip`).
2. The `-shell` variant did not have an entrypoint set.

When I removed the `-shell` variant I also added those additional packages to the main variant, so hopefully 1. should not be a problem.

In most cases it should be possible to set an entrypoint when using the image. I actually use the image in CI scenarios as well. I usually have a `Makefile` for building my projects. In GitHub Actions I then usually do this:

```yaml
[...]
- name: Compile Files
  uses: docker://codello/lilypond:2.24
  with:
    entrypoint: make
    args: ci
[...]
```

I image that something similar would be possible in other CI systems as well. Manually on the command line you could do `docker run -it --entrypoint=bash codello/lilypond:2.24` to get the same behavior as the old `-shell` variant (or you could run your scripts as the entrypoint).

Would this be a feasible solution for you?

**Comment by mauritslamers** [comment]
Thanks for your reply! 

My current setup uses Gitlab and Gitlab Runner like this:

```
test_2.20:
  stage: test
  image: codello/lilypond:2.20-shell
  script:
    - cd tests
    - ./testrunner.s
  allow_failure: true
```
(and so on for every lilypond version I am testing against).

Which means as much as:
- use the codello/lilypond:2.20-shell image
- clone the repo in it (happens automatically)
- run the test runner shell script, which runs Lilypond on all the test files, collects the results and posts them.

Your lilypond-shell docker images are perfect for this. 
The situation is that when I run this with the 2.24 images, I get the following:

```
warning: cannot find file: `sh'
warning: cannot find file: `-c'
warning: cannot find file: `if [ -x /usr/local/bin/bash ]; then
	exec /usr/local/bin/bash 
elif [ -x /usr/bin/bash ]; then
	exec /usr/bin/bash 
elif [ -x /bin/bash ]; then
	exec /bin/bash 
elif [ -x /usr/local/bin/sh ]; then
	exec /usr/local/bin/sh 
elif [ -x /usr/bin/sh ]; then
	exec /usr/bin/sh 
elif [ -x /bin/sh ]; then
	exec /bin/sh 
elif [ -x /busybox/sh ]; then
	exec /busybox/sh 
else
	echo shell not found
	exit 1
fi
```

Setting different entrypoints (which is what gitlab runner also supports) gave me all kinds of other errors such as sh not able to execute binary files when setting "bash" to the entrypoint.
Overriding the entrypoint by "nothing" indeed does solve the issue, but it is not as straightforward as it was.

**Comment by codello** [comment]
I apologize for the delay.

I just ran some tests on gitlab.com to see how the image behaves in their CI. I can reproduce the behavior you described.

> Overriding the entrypoint by "nothing" (as described in [this section](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#override-the-entrypoint-of-an-image) of the gitlab runner config) does solve the issue, but it is not as straightforward as it was.

I feel like it is standard practice for tool-focused Docker images to have the tool binary set as the default entrypoint (For example [restic/restic](https://hub.docker.com/r/restic/restic) or [hashicorp/terraform](https://hub.docker.com/r/hashicorp/terraform)). Given that most (if not all) CI platforms (GitLab included) provide ways to work with these kinds of images I don't really see the value in maintaining a separate tag just to set the entrypoint.
In GitLab specifically this `.gitlab-ci.yml` seems to work (tested using this repo: [codello/lilypond-ci-test](https://gitlab.com/codello/lilypond-ci-test)):
```yaml
test:
  image:
    name: ghcr.io/codello/lilypond:2.24
    entrypoint: [""]
  script:
    - ./compile.sh
    - make
    - lilypond -o direct-test test.ly
  artifacts:
    paths:
      - "*-test.pdf"
```

I agree that it is not quite as straightforward as using the `shell` tag but I don't see the justification to maintain a separate tag for this purpose, sorry.
